# Generated by Django 6.1.1 on 2026-09-05 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotpmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='userotpmodel',
            name='otp_code',
            field=models.PositiveBigIntegerField(verbose_name='کد تایید'),
        ),
    ]
