# Generated by Django 6.1.1 on 2026-09-05 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userotpmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotpmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_password', to=settings.AUTH_USER_MODEL),
        ),
    ]
