# Generated by Django 6.1.1 on 2026-09-05 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_passwordresetotpmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordResetOTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('reset_token', models.UUIDField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_password', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کد تایید بازیابی رمز عبور',
                'verbose_name_plural': 'کدهای تایید بازیابی رمز عبور',
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='PasswordResetOTPModel',
        ),
    ]
