# Generated by Django 6.1.1 on 2026-09-05 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_forgotpasswordresetotpmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgotpasswordresetotpmodel',
            name='is_used',
        ),
        migrations.AlterField(
            model_name='forgotpasswordresetotpmodel',
            name='code',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='forgotpasswordresetotpmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reset_password', to=settings.AUTH_USER_MODEL),
        ),
    ]
