# Generated by Django 6.1.1 on 2026-09-05 19:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_forgotpasswordresetotpmodel_is_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordresetotpmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
    ]
