# Generated by Django 6.1.1 on 2026-09-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_forgotpasswordresetotpmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordresetotpmodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
