services:

  # ============================================================
  # DJANGO
  # ============================================================

  app:
    build:
      context: ./app

    container_name: app
    restart: always

    expose:
      - "8000"

    volumes:
      - ./app:/app
      - ./volumes/media:/volumes/media
      - ./volumes/assets:/volumes/assets

    env_file:
      - .env

    depends_on:
      pgbouncer:
        condition: service_healthy

      redis:
        condition: service_healthy


  # ============================================================
  # NGINX
  # ============================================================

  nginx:
    build:
      context: ./nginx

    container_name: veloshop-nginx
    restart: always

    ports:
      - "80:80"

    depends_on:
      app:
        condition: service_started

    volumes:
      - ./volumes/media:/volumes/media
      - ./volumes/assets:/volumes/assets


  # ============================================================
  # REDIS
  # ============================================================

  redis:
    image: redis:8.2

    container_name: veloshop-redis
    restart: always

    command:
      - redis-server
      - --appendonly
      - "yes"

    volumes:
      - ./volumes/redisdata:/data

    expose:
      - "6379"

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]

      interval: 5s
      timeout: 5s
      retries: 10


  # ============================================================
  # POSTGRESQL PRIMARY
  # ============================================================


  postgres:
    image: postgres:18
    container_name: postgres
    restart: always

    env_file:
      - .env

    ports:
      - "5432:5432"

    volumes:
      - type: bind
        source: ./volumes/dbdata
        target: /var/lib/postgresql


    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U saeed_user -d saeed_db"]
      interval: 5s
      timeout: 5s
      retries: 5


  # ============================================================
  # PGBOUNCER
  # ============================================================

  pgbouncer:
    image: edoburu/pgbouncer:latest

    container_name: pgbouncer
    restart: always

    environment:
      DB_HOST: postgres
      DB_PORT: 5432

      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

      AUTH_TYPE: scram-sha-256

      POOL_MODE: transaction

      MAX_CLIENT_CONN: 200
      DEFAULT_POOL_SIZE: 10
      RESERVE_POOL_SIZE: 5

    expose:
      - "5432"

    depends_on:
      postgres:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h 127.0.0.1 -p 5432 -U ${DB_USER} -d ${DB_NAME}"
        ]

      interval: 5s
      timeout: 5s
      retries: 10