# Generated by Django 6.1.1 on 2026-09-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productscategorymodel',
            name='categories_title_07884d_idx',
        ),
        migrations.AlterField(
            model_name='productscategorymodel',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='productscategorymodel',
            index=models.Index(fields=['title'], name='categories_title_e17cea_idx'),
        ),
        migrations.AddIndex(
            model_name='productscategorymodel',
            index=models.Index(fields=['slug'], name='categories_slug_b4303a_idx'),
        ),
    ]
