# Generated by Django 6.1.1 on 2026-09-07 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_productscategorymodel_categories_title_07884d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscategorymodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.productscategorymodel'),
        ),
    ]
