# Generated by Django 6.1.1 on 2026-09-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_productscategorymodel_parent'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productscategorymodel',
            name='categories_slug_b4303a_idx',
        ),
    ]
