# Generated by Django 6.1.1 on 2026-09-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_productscategorymodel_categories_title_07884d_idx_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productmodel',
            new_name='products_is_acti_706d22_idx',
            old_name='products_pr_is_acti_867533_idx',
        ),
        migrations.RenameIndex(
            model_name='productmodel',
            new_name='products_is_spec_b97705_idx',
            old_name='products_pr_is_spec_23c5cc_idx',
        ),
        migrations.RenameIndex(
            model_name='productmodel',
            new_name='products_most_vi_97abea_idx',
            old_name='products_pr_most_vi_d852da_idx',
        ),
        migrations.RenameIndex(
            model_name='productmodel',
            new_name='products_sales_fd66fe_idx',
            old_name='products_pr_sales_e3423c_idx',
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['title'], name='products_title_6a4e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['slug'], name='products_slug_5e91f2_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['discount'], name='products_discoun_97d669_idx'),
        ),
        migrations.AlterModelTable(
            name='productmodel',
            table='products',
        ),
    ]
