# Generated by Django 6.1.1 on 2026-09-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_productscategorymodel_categories_title_07884d_idx_and_more'),
        ('products', '0002_rename_products_pr_is_acti_867533_idx_products_is_acti_706d22_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='productmodel',
            name='products_is_acti_706d22_idx',
        ),
        migrations.RemoveIndex(
            model_name='productmodel',
            name='products_is_spec_b97705_idx',
        ),
        migrations.RemoveIndex(
            model_name='productmodel',
            name='products_most_vi_97abea_idx',
        ),
        migrations.RemoveIndex(
            model_name='productmodel',
            name='products_sales_fd66fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='productmodel',
            name='products_title_6a4e5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='productmodel',
            name='products_slug_5e91f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='productmodel',
            name='products_discoun_97d669_idx',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='description_short',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['title', 'slug', 'is_active', 'is_available', 'is_special', 'most_viewed', 'sales', 'created_at'], name='products_title_fc74d2_idx'),
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='discount',
        ),
    ]
