# Generated by Django 6.1.1 on 2026-09-09 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartproductitemmodel_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproductitemmodel',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='cart.cartproductmodel'),
        ),
    ]
