# Generated by Django 6.1.1 on 2026-09-09 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartproductitemmodel_cart'),
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproductmodel',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_cart', to='coupon.couponmodel'),
        ),
    ]
